### ISSUE TITLE
Architecture Review: Logging in and Deploying to Machines Without Root

### ISSUE THREAD

**Issue by grahamc** [Holo-Host/bugs-n-issues#11]
Today administration is done by logging in to machines as root, and root has all the admin's keys preloaded.

As a first step, for each key in this list we'll create a user who is in the "wheel" group, with their assigned SSH key:

https://github.com/Holo-Host/holo-nixpkgs/blob/75c7d1b1d346dcfde27d24a60c3bdf19329896b3/profiles/logical/holo/default.nix#L12-L29

**Comment by alastairong** [comment]
I would like more context as to what "auditing and forensics" means in this context. E.g. are we talking about tracing bugs? Are we talking about who is actually accessing the machine? I.e. access control & security? Etc...

**Comment by grahamc** [comment]
We'll start working on this ticket by creating individual users for admins, each of which can use sudo to become root. This will grant them the same level of privileges but defaulting to fewer. Later, Holo can review the logs to identify who is becoming root and make a greater policy decision later.

**Comment by grahamc** [comment]
Let's start with these keys and break them out into other users: https://github.com/Holo-Host/holo-nixpkgs/blob/84fb3e2f64b5e44cdef579db89a2912a244f511a/profiles/logical/holo/default.nix

**Comment by peeech** [comment]
I will add one more user to this list tomorrow and merge it into develop.

**Comment by alastairong** [comment]
What is the user experience that results from this?

Is it that every user, such as myself, would log in with their own username? E.g.

`ssh alastair@188.166.21.56` rather than `ssh root@188.166.21.56`?

And that I would only have root access if running with `sudo`?

**Comment by alastairong** [comment]
And is the scope everything in Holo-nixpkgs? I.e. also holoports, not just the centralised servers?

**Comment by firestack** [comment]
> What is the user experience that results from this?
> 
> Is it that every user, such as myself, would log in with their own username? E.g.
> 
> `ssh alastair@188.166.21.56` rather than `ssh root@188.166.21.56`?
> And that I would only have root access if running with `sudo`?
> 
> AND that I still get access via defined SSH keys rather than login/pw?

Yes, it is expected that any actions which previously required `root` should be logged into using the existing SSH key and corresponding username from the configuration files. Then the user can use password-less `sudo` to elevate to `root` access.

> And is the scope everything in Holo-nixpkgs? I.e. also holoports, not just the centralised servers?

Initially the scope of the first PR should only be central infrastructure in `holo-nixpkgs`, and only the configuration profiles contained within [this folder](https://github.com/Holo-Host/holo-nixpkgs/tree/develop/profiles/logical/holo). From the import graph within `holo-nixpkgs` it does not seem like holoports are affected by this change. Should we expand the scope to include holoports as well?

**Comment by peeech** [comment]
I can confirm that https://github.com/Holo-Host/holo-nixpkgs/pull/1140 is working as expected and we are ready for PR 2/2.

**Comment by peeech** [comment]
I think that by closing #33 we have achieved the goals of this ticket. Let me know if you agree @alastairong @grahamc , I'd like to close it ASAP

**Comment by peeech** [comment]
ha, it is actually already closed :-)
