### ISSUE TITLE
Manage fan settings via nixOS

### ISSUE THREAD

**Issue by alastairong** [Holo-Host/bugs-n-issues#3]
@grahamc Not strictly speaking an issue, but if you have time while waiting for hydra to get stuck again we would love some help configuring holoport fans via nixpkgs.

We already have a set of better calibrated fan settings tested out but need to configure it.

**Comment by alastairong** [comment]
@grahamc Now that you have a HoloPort, can this be the next ticket we start on once log aggregation is complete?

CC: @peeech

**Comment by grahamc** [comment]
You got it @alastairong, sounds like a good choice.

**Comment by firestack** [comment]
Hi @alastairong, @peeech, we've got some updates

After receiving and setting up the Holoport and access to the Holoport, we've been inspecting and experimenting with the fan capabilities onboard. We've confirmed that the chip controlling power and PWM of the `CPU_FAN` header is the `IT8772E` which can be accessed using the driver from the kernel module `it87`. 

This driver provides an interface accessible though `sysfs` 
```
/sys/class/hwmon/hwmon3 ->/sys/devices/platform/it87.2624/hwmon/hwmon3
```
as well as allows utilities from `lm_sensors`: `sensors`, `pwmcontrol`, and `fancontrol` to _read_ the `CPU_FAN` values, including RPM and Voltages that the `it8772` is responsible for. 

To be able to write to the PWM control of the IT8772, we must first enable manual mode and disable "Smart Guardian" mode.

> [The fan speed control features are limited to manual PWM mode. Automatic “Smart Guardian” mode control handling is only implemented for older chips (see below.) However if you want to go for “manual mode” just write `1` to `pwmN_enable`.](https://www.kernel.org/doc/html/latest/hwmon/it87.html#fan-speed-control)

Before writing `1` to `pwmN_enable` the file contains `2`, to indicate that it is in smart guardian mode.
When the file contains `1`, it is in manual PWM control mode.
When the file contains `0`, it is in full speed mode.

The Holoport resets the `IT8772E` to `Automatic Smart Guardian Mode` on reboot. And attempting to put `2` into `pwmN_enable` file results in `write error: Invalid argument`.

In manual mode, the `pwmcontrol` utility seems to have decent control over the fan onboard the holoport.
<details>
<summary>PWM Control Test Results</summary>

```
Testing pwm control hwmon3/pwm2 ...
  hwmon3/fan2_input ... speed was 4166 now 870
    It appears that fan hwmon3/fan2_input
    is controlled by pwm hwmon3/pwm2
Would you like to generate a detailed correlation (y)?
    PWM 255 FAN 4166
    PWM 240 FAN 4041
    PWM 225 FAN 3835
    PWM 210 FAN 3668
    PWM 195 FAN 3479
    PWM 180 FAN 3292
    PWM 165 FAN 3096
    PWM 150 FAN 2884
    PWM 135 FAN 2657
    PWM 120 FAN 2419
    PWM 105 FAN 2177
    PWM 90 FAN 1934
    PWM 75 FAN 1638
    PWM 60 FAN 1360
    PWM 45 FAN 1027
    PWM 30 FAN 884
    PWM 28 FAN 882
    PWM 26 FAN 882
    PWM 24 FAN 882
    PWM 22 FAN 883
    PWM 20 FAN 885
    PWM 18 FAN 886
    PWM 16 FAN 886
    PWM 14 FAN 886
    PWM 12 FAN 886
    PWM 10 FAN 883
    PWM 8 FAN 883
    PWM 6 FAN 883
    PWM 4 FAN 882
    PWM 2 FAN 883
    PWM 0 FAN 883
```
</details>

And `pwmconfig` generates the following `fancontrol` configuration for our holoport.

<details>
<summary>/etc/fancontrol</summary>

```
[root@hpos:~]# cat /etc/fancontrol
# Configuration file generated by pwmconfig, changes will be lost
INTERVAL=10
DEVPATH=hwmon2=devices/platform/coretemp.0 hwmon3=devices/platform/it87.2624
DEVNAME=hwmon2=coretemp hwmon3=it8772
FCTEMPS=hwmon3/pwm2=hwmon2/temp1_input
FCFANS=hwmon3/pwm2=hwmon3/fan2_input
MINTEMP=hwmon3/pwm2=20
MAXTEMP=hwmon3/pwm2=60
MINSTART=hwmon3/pwm2=150
MINSTOP=hwmon3/pwm2=0
```
</details>

With current capabilities in NixOS, we could control the fan's via [the nixos option hardware.fancontrol.config](https://search.nixos.org/options?channel=unstable&show=hardware.fancontrol.config&from=0&size=50&sort=relevance&type=packages&query=fancontrol) and may be able to get some satisfying results using `fancontrol`, this inherently has limitations as it's a software solution, and must poll the sensors and then update the fan speeds according to the configuration defined for `fancontrol`.

The current state of the driver for the `IT87` family is limited in terms of the capabilities the device `IT8772` is able to do. Currently, [the numbers displayed in the BIOS](https://github.com/Holo-Host/bugs-n-issues/issues/3#issuecomment-971510545) for the fan ramp are related to the Smart Guardian controls on the `IT8772E`, and control of the smart guardian fan control ramp is not currently available in the `it87` module. Using a [spec sheet for a similar controller](https://master-chip.ru/files/e0ec6325-b20e-079c-f0ce-275a3ec60f51/IT8772E-ITE.pdf), It may be possible for us to research and implement more functionality in the `it87` linux kernel driver to allow us to have better control over the `IT8772E` chip, such as providing software access to the Smart Guardian fan control ramps provided in the BIOS though the kernel driver. 

Thanks for reading! Please let us know how you'd like to proceed, we can also schedule a call to discuss further.

**Comment by alastairong** [comment]
Thanks for this thorough investigation. I have a few questions:

1. How much experience do you have with implementing kernel drivers like this? Is this a realistic course of action for a production environment?

2. What is the user experience drawback of the `fancontrol` software solution? Does it add significantly more CPU load? Is it slower to react? Is it likely to never converge on equilibrium fan speeds?

3. Is there anything in particular about the fan settings we have chosen that makes this more difficult than it could be? We can revisit the settings to choose something potentially more simple? E.g. leave some of the defaults so we have fewer settings to manage.

**Comment by firestack** [comment]
> 1. How much experience do you have with implementing kernel drivers like this? Is this a realistic course of action for a production environment with the resources we have?

Neither @grahamc or I have experience writing linux kernel drivers or modules, thus it'd probably be an expensive research project, and something we should not pursue at this time. If this became important or required, we could explore hiring someone with more direct experience.

> 2. What is the user experience drawback of the `fancontrol` software solution? Does it add significantly more CPU load? Is it slower to react? Is it likely to never converge on equilibrium fan speeds?

`fancontrol` by default sets it's `INTERVAL` to `10`, which means it will poll the temperature sensors available to `lm_sensors` and update the fan PWM setting, every 10 seconds. We can configure this to give us control over how much CPU time is being spent on managing fans and how quickly the fans react to changes in temperature.

[If we were to graph the fan `rpm`/`pwm` against the temperature of the CPU, we would find it looks a bit like a Riemann sum. ](https://www.desmos.com/calculator/rvoqumsywg) Where we measure every `INTERVAL` and set the `PWM` value, and then wait, at the same `PWM` value, until the next `INTERVAL`, in which we'd poll the temperature again and update the `PWM` value. This lag can be reduced at the cost of more polling and CPU time, we currently do not have profiling of how much overhead `fancontrol` adds during it's update period, but it is likely minimal. (I intend to profile this and should have some better information on `fancontrol` performance tomorrow)

> 3. Is there anything in particular about the fan settings we have chosen that makes this more difficult than it could be? We can revisit the settings to choose something potentially more simple? E.g. leave some of the defaults so we have fewer settings to manage.

As far as I can tell, and I have not had _access_ to the BIOS yet, my initial impression is that the fan settings in the BIOS are a good default and fallback, and they don't seem to affect the ability for linux to control the PWM values aside from first requiring that we put `1` into `pwm2_enable`, Which we should be able to do as a service before fan control runs. I think it's best to leave the bios settings at a reasonable default in case a user disables `fancontrol` and wants to reboot to resume `Smart Guardian Mode`.

**Comment by alastairong** [comment]
@firestack 

>  fan settings in the BIOS are a good default and fallback

Unfortunately they are not, because:
1. The fan start temperature limit is set to only a few degrees hotter than idle. It turns out that 8th gen Intel (Kaby Lake) runs hotter than typical for this class of chip (probably to compensate for their ongoing process node issues)
2. The fan ramp is basically to go instantly to full speed.

This combination means almost anything meaningful workload leads to the fan being on full blast.

It sounds like the software solution leads to a similar outcome as a BIOS/kernel solution from a user perspective? If so, that sounds like the best approach to me.

CC: @peeech

**Comment by alastairong** [comment]
Ah ok. Thanks for clarifying :)

**Comment by firestack** [comment]
Hey @alastairong ! 
I've opened a PR (https://github.com/Holo-Host/holo-nixpkgs/pull/1235) which should address most everything we've talked about in this issue. I'd appreciate any and all feedback and can make changes as necessary!

**Comment by alastairong** [comment]
Thanks @firestack! What type of feedback are you expecting? Do you want me to actually switch some HPs to it and see what happens?

**Comment by firestack** [comment]
@alastairong I'm mostly interested in knowing if y'all would prefer that the `fancontrol.nix` module be placed somewhere else other than `profiles/physical/hpos/holoport/fancontrol.nix`. This spot made sense to me but it may not be correct for y'all's organization. 
I also think it's important to scrutinize the import in `holoport-plus` (`../holoport/fancontrol.nix`) to make sure it fits organization standards in the repository.

Other than that, everything should be good.

**Comment by alastairong** [comment]
I responded directly in the PR.

**Comment by peeech** [comment]
Closing via https://github.com/Holo-Host/holo-nixpkgs/pull/1235
