### ISSUE TITLE
Hydra fails to run on latest develop

### ISSUE THREAD

**Issue by peeech** [Holo-Host/bugs-n-issues#38]
As a part of an effort to simplify branches in `holo-nixpkgs` repo we are switching Hydra to master channel and deleting hydra branch. This requires following steps:
- [x] create hydra-dev server which follows develop channel
- [ ] make sure hydra-dev works as expected

**Comment by peeech** [comment]
My latest effort to switch hydra to develop were unsuccessful. Unfortunately I have no logs, but it will become apparent right away in `journalctl`.

We can re-purpose a `128.199.43.59` server which still follows `hydra-19.09` channel. 
Ideally I would love to have hydra-dev:
- [ ] follow `develop` channel
- [ ] be available at https://hydra-dev.holo.host
- [ ] not post any updates to the world (github status, cache builds)

**Comment by peeech** [comment]
Currently `128.199.43.59` is wrapped with firewall which allows port 22 only on a level of an instance provider

**Comment by grahamc** [comment]
The final result here is we're going to:

1. Fix the develop branch where Hydra runs successfully from the develop branch.
2. In the future, there will be only one Hydra instance running from the master branch.
3. PRs addressing problems of Hydra itself will go directly to the master branch.

**Comment by peeech** [comment]
Because of #40 and certain urgency for having working hydra I have switched instances between hydra and hydra-dev. So currently `128.199.43.59` is our production Hydra and is available at `https://hydra.holo.host`. `188.166.39.133` is an instance where @cole-h is testing new work.

**Comment by firestack** [comment]
Yesterday I started working on this on the `hydra-dev.holo.host` server, experimenting to find if the current develop branch works for hydra. 

Both hydra servers have evaluated the latest `develop` branch and are succeeding for the `holo-hydra` constituent
https://hydra.holo.host/eval/1958094?filter=hydra&compare=1957786&full=
https://hydra-dev.holo.host/eval/2312178?filter=hydra&compare=2311970&full=

When deploying the latest HEAD of `develop` we encountered an issue with activation. Specifically
```
[detsys@hydra:~/src/holo-nixpkgs]$ sudo ./nixos-develop-result/bin/switch-to-configuration test
activating the configuration...
setting up /etc...
warning: 'ping-store' is a deprecated alias for 'store ping'
error: experimental Nix feature 'nix-command' is disabled; use '--experimental-features nix-command' to override
Activation script snippet 'nix' failed (1)
reloading user units for root...
reloading user units for detsys...
setting up tmpfiles
```

The fix, is to apply [this commit from upstream](https://github.com/NixOS/nixpkgs/commit/9bf75a27f46f6b330b02ce25ac34d4d2ede3ba4a), where the snippet was overridden inside of `holo-nixpkgs`

We have implemented and PR-ed this change here: 

After testing this PR, I then ran 
```
sudo hydra-eval-jobs -I . release.nix
```
Multiple times, and eventually ran [3 parallel invocations](https://github.com/Holo-Host/holo-nixpkgs/blob/develop/profiles/logical/holo/hydra/master/default.nix#L21) of `hydra-eval-jobs` to attempt to affect the memory usage on the machine and see if we're still OOM-ing or having any issues with hydra being run from `develop`.

I was able to watch and confirm all three instances of `hydra-eval-jobs` succeed, without any build & execution failures.

**Comment by peeech** [comment]
I can confirm that #1200 solved Hydra build issues.

**Comment by peeech** [comment]
After switching `hydra-develop` to develop channel (which now contains fix from #1200) `hydra-init` fails with an error:
```
Mar 28 12:42:14 hydra systemd[1]: Starting hydra-init.service...
Mar 28 12:42:14 hydra runuser[2862411]: pam_unix(runuser:session): session opened for user postgres(uid=71) by (uid=0)
Mar 28 12:42:14 hydra hydra-init-pre-start[2862412]: psql: error: FATAL:  database "hydra" does not exist
Mar 28 12:42:14 hydra runuser[2862411]: pam_unix(runuser:session): session closed for user postgres
Mar 28 12:42:14 hydra systemd[1]: hydra-init.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
Mar 28 12:42:14 hydra systemd[1]: hydra-init.service: Failed with result 'exit-code'.
Mar 28 12:42:14 hydra systemd[1]: Failed to start hydra-init.service.
```

**Comment by grahamc** [comment]
It looks like we upgraded it to 11.x and now we just need to upgrade it to 13: https://github.com/Holo-Host/bugs-n-issues/issues/9#issuecomment-976734707

**Comment by grahamc** [comment]
Kayla and I walked through the postgresql update procedures and this issue with hydra-develop appears to be fixed :+1:

**Comment by grahamc** [comment]
@peeech I think we're all squared away here. There aren't super clear conditions under which we can call this ticket done, but I think we're there :).

**Comment by peeech** [comment]
I can confirm Hydra on develop is working as expected. As per our decision I am killing `hydra-dev.holo.host` and we have only one instance at `hydra.holo.host` which follows develop channel (of itself :-) )
