### ISSUE TITLE
Hydra is unable to evaluate new jobs

### ISSUE THREAD

**Issue by peeech** [Holo-Host/bugs-n-issues#40]
Hydra `188.166.39.133` which follows channel `hydra` fails to evaluate new PRs with an error:
```
Mar 17 12:38:40 hydra hydra-evaluator[1076244]: (holo-nixpkgs:develop) Evaluating...
Mar 17 12:38:59 hydra hydra-evaluator[1075419]: (holo-nixpkgs:1186) Evaluating...
Mar 17 12:38:59 hydra hydra-evaluator[1075418]: (holo-nixpkgs:1185) Evaluating...
Mar 17 12:39:53 hydra systemd[1]: hydra-evaluator.service: A process of this unit has been killed by the OOM killer.
Mar 17 12:39:53 hydra systemd[1]: hydra-evaluator.service: Main process exited, code=exited, status=1/FAILURE
```
As a consequence new channels are not created from PRs:
<img width="1039" alt="Screen Shot 2022-03-17 at 13 03 18" src="https://user-images.githubusercontent.com/13788111/158811237-42075148-d549-4c6d-9cdf-a0f0e7f39ce3.png">

**Comment by peeech** [comment]
Hey @cole-h I added requested key for user root. I think you should be able to log in.

**Comment by peeech** [comment]
I have switched https://hydra.holo.host to the server `128.199.43.59` hoping that this would allow us to have working instance of hydra. Funny enough this old instance of hydra (still running Hydra from 2019-08-30) is also unable to evaluate latest PRs. This makes me think that an error in the code stems from the code in [this file](https://github.com/Holo-Host/holo-nixpkgs/blob/develop/release.nix), which might be creating some sort of circular dependencies which makes an evaluation loop forever and eventually OOM?

I have added the detsys CA key to the root user on `128.199.43.59` if you ever want to access it for analysis.

**Comment by cole-h** [comment]
Confirmed the key works for both -- thanks! We'll take a look and keep you updated. Sorry that this is happening...

Also, I think that `128.199.43.59` is "working", at least more than the other machine -- it's not OOMing, but none of the builders appear to be handling build jobs... (https://hydra.holo.host/status shows "no running jobs")

**Comment by cole-h** [comment]
I think I've found the issue with the OOMing: It appears that the `constitute` function behaves poorly. I don't know why this is just appearing now, but I think I can fix it. (The weirdest part of this whole thing is that I was unable to reproduce the excessive memory consumption locally...!)

**Comment by cole-h** [comment]
I think https://github.com/Holo-Host/holo-nixpkgs/pull/1189 is in a good place now -- I was able to evaluate the `release.nix` expression on both `188.` and `128.` without hitting any memory constraints.
