### ISSUE TITLE
`nix-channel --update` fails to fetch updated channel

### ISSUE THREAD

**Issue by peeech** [Holo-Host/bugs-n-issues#42]
When I execute `nix-channel --update` on Hydra it fails to update to the tip of a channel

### How to reproduce
- ssh into Hydra
- run `nix-channel --update`
- go to `/nix/var/nix/profiles/per-user/root/channels` and follow `holo-nixpkgs` link
If you compare a code in `holo-nixpkgs` directory with the code in rev of holo-nixpkgs that is at the [tip of develop](https://hydra.holo.host/jobset/holo-nixpkgs/develop) you will see that the code is not updated locally.

The question here is how to force nixOs to fetch new channel? Is there a way to disable some potential caching?

**Comment by firestack** [comment]
Hi @peeech,
I've done some investigation into the issue and have attempted to reproduce unsuccessfully. 

A quick question before proceeding, @peeech did you login with `root` or use `sudo` to execute `nix-channel --update`?

I ran `sudo nix-channel --update` at `2022-04-01 11:24:00-04:00`
and was unable to tell a difference between between `holo-nixpkgs/develop` and `/nix/var/nix/profiles/per-user/root/channels/holo-nixpkgs`.
```
[detsys@hydra:~/src/holo-nixpkgs]$ git -C /home/detsys/src/holo-nixpkgs/ show
commit 0ed7bdcd83b5e3d50f370ff027ad16249ada17cd (HEAD -> develop, up/develop)
Merge: a6eda449 4843ca2c
Author: Alastair Ong <alastair.ong@gmail.com>
Date:   Fri Apr 1 11:05:22 2022 +0100

    Merge pull request #1202 from Holo-Host/hdk-v0.0.126

    Bump holochain v0.0.131

[detsys@hydra:~/src/holo-nixpkgs]$ diff -r -q  /nix/var/nix/profiles/per-user/root/channels/holo-nixpkgs/ /home/detsys/src/holo-nixpkgs/
Only in /home/detsys/src/holo-nixpkgs/: .git
```

> The question here is how to force NixOS to fetch new channel? Is there a way to disable some potential caching?

The manual here https://nixos.org/manual/nix/stable/command-ref/conf-file.html describes how tarball "staleness" is understood within nix (under the `--tarball-ttl` section).

If we wanted to force the `holo-nixpkgs-auto-upgrade` service to check the server for every invocation of `nix-channel --update` we can add `--tarball-ttl 0` [here](https://github.com/Holo-Host/holo-nixpkgs/blob/0ed7bdcd83b5e3d50f370ff027ad16249ada17cd/modules/system/holo-nixpkgs/auto-upgrade.nix#L39).

@grahamc also suggested that if this persists in the future it's possible to delete the `root` user's channel cache info by deleting files within `/root/.cache/nix`.
