### ISSUE TITLE
Hydra evaluates PRs every 10s

### ISSUE THREAD

**Issue by peeech** [Holo-Host/bugs-n-issues#43]
Currently Hydra checks for new code on each PR [every 10s](https://github.com/Holo-Host/holo-nixpkgs/blob/develop/profiles/logical/holo/hydra/master/specs/holo-nixpkgs.json#L2). This generates an unnecessary constant CPU load of 50%.

It would be beneficial to explore a possibility of using github webhooks for each push to a PR or branch.

**Comment by grahamc** [comment]
Hey @peeech, you bet! This is actually quite easy to set up, and your jobsets are already configured on the Hydra end to support it.

I just learned that process is documented in the Hydra repo: https://github.com/NixOS/hydra/blob/c44d9d9e917f8f02ddb5c01a8620c439993540b6/doc/manual/src/webhooks.md

but it comes down t going to https://github.com/Holo-Host/holo-nixpkgs/settings and in the Webhooks tab click on Add webhook.

* In Payload URL fill in: `https://hydra.holo.host/api/push-github`
* In Content type switch to application/json.
* The Secret field can stay empty.
* For "Which events would you like to trigger this webhook?" keep the default option for events on Just the push event.

Once this is all set, the evaluation frequency can reduced significantly.

**Comment by peeech** [comment]
I have set up a webhook on github, I can see successful webhook deliveries with response body from Hydra:
```
{"jobsetsTriggered":["holo-nixpkgs:1237","holo-nixpkgs:1243","holo-nixpkgs:master","holo-nixpkgs:alpha","holo-nixpkgs:1127","holo-nixpkgs:1246","holo-nixpkgs:1229","holo-nixpkgs:1247","holo-nixpkgs:1251","holo-nixpkgs:1240","holo-nixpkgs:872","holo-nixpkgs:.jobsets","holo-nixpkgs:1235","holo-nixpkgs:hctesting","holo-nixpkgs:1209","holo-nixpkgs:hydra","holo-nixpkgs:develop","holo-nixpkgs:995","holo-nixpkgs:staging"]}
```

From what I understand we need to disable polling on Hydra to actually remove a 10s query, don't we?

**Comment by grahamc** [comment]
That's great, yes -- next step would be to make the check interval of your jobsets either 0 for inactive, or perhaps 3600 in case a webhook event is missed.

**Comment by peeech** [comment]
I have updated interval for jobsets created via `jobsets.nix`. Do I have to update `checkinterval` anywhere else for `release.nix`? @grahamc

**Comment by grahamc** [comment]
Correction: there was another jobset which I manually bumped to 600s: https://hydra.holo.host/jobset/holoportOS/master#tabs-configuration

**Comment by peeech** [comment]
Great. Logs are confirming that there is no more 10s interval pulls from evaluator. Closing this one as well.
